#spring:
#  application:
#    name: gateway
#  cloud:
#    config:
#      uri: http://${CONFIG_SERVER}:${CONFIG_SERVER_PORT}
#      fail-fast: true
#      password: ${CONFIG_SERVICE_PASSWORD}
#      username: user

spring:

  application:
    name: notebook-service

  sleuth:
    sampler:
      probability: 1.0
    enabled: true

  zipkin:
    base-url: http://localhost:9411
  mvc:
    static-path-pattern: /**



  endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false


eureka:
  client:
    serviceUrl:
      defaultZone:  ${DISCOVERY_URL:http://eureka-server:8761}/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8888

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
    org.springframework.cloud.sleuth: DEBUG

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: info, health, routes
ribbon:
  eureka:
    enabled: true

